/**
 * blueprint-playbooks.ts — Catalogue complet des Playbooks Blueprint
 * Source: DeepSearch Gaps & Playbooks (DEEPSEARCH-GAPS-PLAYBOOKS-RESULTS.md)
 *       + blueprint-config.ts (playbooks existants)
 *       + MasterPlaybooksPage.tsx (playbooks universels et sectoriels)
 *
 * 46 playbooks existants + 97 nouveaux = 143 playbooks total
 * 12 departements x phases x tiers
 */

// ── Interface ──

export interface BlueprintPlaybook {
  id: string;
  name: string;
  description: string;
  botCode: string;
  blueprintSection: string;
  phase: "startup" | "scaleup" | "exitup";
  phases: ("startup" | "scaleup" | "exitup")[];
  minTier: number;
  maxTier: number;
  complexity: "simple" | "moyen" | "complexe";
  estimatedDuration: string;
  deliverables: string[];
  source: "existant" | "nouveau";
}

// ── Donnees ──

export const BLUEPRINT_PLAYBOOKS: BlueprintPlaybook[] = [

  // ============================================================
  // CEOB — CarlOS — Direction (10 existants + 7 nouveaux = 17)
  // ============================================================

  // -- Existants CEOB --
  {
    id: "PB-CEOB-001",
    name: "Plan strategique 3-5 ans",
    description: "Structure la vision a long terme via l'analyse des capacites internes, l'identification des priorites de croissance et la creation d'un plan d'action mesurable.",
    botCode: "CEOB",
    blueprintSection: "objectifs_vitaa",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Plan strategique 3-5 ans", "Axes strategiques directeurs", "Tableau de bord OKR"],
    source: "existant",
  },
  {
    id: "PB-CEOB-002",
    name: "Preparation au conseil d'administration",
    description: "Structuration de la gouvernance formelle incluant la mise en place d'un CA, des comites et des rituels de gouvernance.",
    botCode: "CEOB",
    blueprintSection: "gouvernance",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 mois",
    deliverables: ["Charte du CA", "Reglements generaux", "Calendrier des seances"],
    source: "existant",
  },
  {
    id: "PB-CEOB-003",
    name: "Due diligence vendeur",
    description: "Preparation complete de la data room et des documents necessaires pour la vente de l'entreprise.",
    botCode: "CEOB",
    blueprintSection: "risques_sortie",
    phase: "exitup",
    phases: ["exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Data room structuree", "Memorandum d'information", "Checklist due diligence"],
    source: "existant",
  },
  {
    id: "PB-CEOB-004",
    name: "Transformation numerique globale",
    description: "Planification et execution de la numerisation de bout en bout, incluant l'audit de maturite et la gestion du changement.",
    botCode: "CEOB",
    blueprintSection: "objectifs_vitaa",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Audit maturite numerique", "Feuille de route transformation", "Plan de gestion du changement"],
    source: "existant",
  },
  {
    id: "PB-CEOB-005",
    name: "Fusion / Acquisition — Integration post-merger",
    description: "Orchestration de l'integration post-acquisition incluant les synergies, la retention des talents et l'integration des systemes.",
    botCode: "CEOB",
    blueprintSection: "gouvernance",
    phase: "exitup",
    phases: ["scaleup", "exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Plan d'integration 100 jours", "Matrice des synergies", "Plan de retention talents"],
    source: "existant",
  },
  {
    id: "PB-CEOB-006",
    name: "Programme de releve et succession",
    description: "Identification et preparation des successeurs pour les postes cles de direction.",
    botCode: "CEOB",
    blueprintSection: "gouvernance",
    phase: "exitup",
    phases: ["scaleup", "exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "6-18 mois",
    deliverables: ["Plan de succession", "Matrice des competences direction", "Programme de mentorat"],
    source: "existant",
  },
  {
    id: "PB-CEOB-007",
    name: "Restructuration financiere / redressement",
    description: "Actions de survie incluant la restructuration des couts, la renegociation de dettes et la stabilisation de la tresorerie.",
    botCode: "CEOB",
    blueprintSection: "finances",
    phase: "startup",
    phases: ["startup", "scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Plan de redressement", "Budget de crise", "Echeancier de renegociation"],
    source: "existant",
  },
  {
    id: "PB-CEOB-008",
    name: "Expansion internationale",
    description: "Structuration de l'expansion hors Quebec incluant l'analyse des marches cibles et les programmes d'accompagnement.",
    botCode: "CEOB",
    blueprintSection: "objectifs_vitaa",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Etude de marche international", "Plan d'entree par marche", "Dossier Panorama IQ"],
    source: "existant",
  },
  {
    id: "PB-CEOB-009",
    name: "Programme ESG complet",
    description: "Mise en place d'une strategie ESG couvrant l'empreinte carbone, la diversite et la gouvernance responsable.",
    botCode: "CEOB",
    blueprintSection: "culture_esg",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Bilan carbone", "Politique DEI", "Rapport ESG annuel"],
    source: "existant",
  },
  {
    id: "PB-CEOB-010",
    name: "Marque employeur et attraction",
    description: "Construction d'une marque employeur forte pour attirer et retenir les meilleurs talents.",
    botCode: "CEOB",
    blueprintSection: "culture_esg",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 mois",
    deliverables: ["Proposition de valeur employeur", "Strategie reseaux sociaux RH", "Kit d'accueil employes"],
    source: "existant",
  },

  // -- Nouveaux CEOB (DeepSearch) --
  {
    id: "PB-CEOB-011",
    name: "Gestion de crise et plan de continuite (BCP)",
    description: "Preparer l'entreprise a survivre a une crise majeure en elaborant un Plan de Continuite des Affaires robuste.",
    botCode: "CEOB",
    blueprintSection: "risques_sortie",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["Plan de continuite des affaires (PCA)", "Analyse d'impact (BIA)", "Protocoles de communication de crise"],
    source: "nouveau",
  },
  {
    id: "PB-CEOB-012",
    name: "Tableau de bord CEO et gouvernance decisionnelle",
    description: "Mise en place des rituels de gouvernance et de l'instrumentation BI du dirigeant pour un pilotage eclaire.",
    botCode: "CEOB",
    blueprintSection: "kpis_direction",
    phase: "scaleup",
    phases: ["startup", "scaleup", "exitup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 semaines",
    deliverables: ["Tableau de bord executif", "Grille KPI par departement", "Calendrier de revues"],
    source: "nouveau",
  },
  {
    id: "PB-CEOB-013",
    name: "Preparation a la vente et due diligence",
    description: "Structurer la demarche de vente de l'entreprise pour maximiser la valorisation et satisfaire les exigences de l'acquereur.",
    botCode: "CEOB",
    blueprintSection: "risques_sortie",
    phase: "exitup",
    phases: ["exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Data room complete", "Memorandum confidentiel", "Modele de valorisation"],
    source: "nouveau",
  },
  {
    id: "PB-CEOB-014",
    name: "Strategie ESG et responsabilite sociale",
    description: "Integrer les criteres environnementaux, sociaux et de gouvernance dans la strategie globale de l'entreprise.",
    botCode: "CEOB",
    blueprintSection: "culture_esg",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 mois",
    deliverables: ["Politique ESG", "Bilan carbone simplifie", "Plan d'action developpement durable"],
    source: "nouveau",
  },
  {
    id: "PB-CEOB-015",
    name: "Internationalisation et expansion hors Quebec",
    description: "Structurer la demarche d'exportation en tirant parti des programmes comme Panorama d'Investissement Quebec.",
    botCode: "CEOB",
    blueprintSection: "objectifs_vitaa",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Etude de faisabilite export", "Plan d'entree par marche", "Dossier programme Panorama"],
    source: "nouveau",
  },
  {
    id: "PB-CEOB-016",
    name: "Vision, mission, valeurs — atelier de definition",
    description: "Atelier structure pour definir ou redefinir le noyau identitaire de l'entreprise avec l'equipe fondatrice.",
    botCode: "CEOB",
    blueprintSection: "profil",
    phase: "startup",
    phases: ["startup"],
    minTier: 1,
    maxTier: 5,
    complexity: "simple",
    estimatedDuration: "1-2 semaines",
    deliverables: ["Enonce de mission", "Enonce de vision", "Charte des valeurs"],
    source: "nouveau",
  },
  {
    id: "PB-CEOB-017",
    name: "Planification strategique annuelle (OKR/VITAA)",
    description: "Rituel annuel de planification des objectifs mesurables alignes sur les 5 piliers VITAA.",
    botCode: "CEOB",
    blueprintSection: "objectifs_vitaa",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 semaines",
    deliverables: ["OKRs trimestriels", "Tableau de bord VITAA", "Plan d'execution annuel"],
    source: "nouveau",
  },

  // ============================================================
  // CTOB — Tim — Technologie (2 existants + 8 nouveaux = 10)
  // ============================================================

  // -- Existants CTOB --
  {
    id: "PB-CTOB-001",
    name: "Audit securite annuel",
    description: "Evaluation complete de la posture de securite informatique incluant tests de penetration et recommandations.",
    botCode: "CTOB",
    blueprintSection: "securite_applicative",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 semaines",
    deliverables: ["Rapport d'audit securite", "Plan de remediation", "Score de maturite securite"],
    source: "existant",
  },
  {
    id: "PB-CTOB-002",
    name: "Migration cloud et modernisation TI",
    description: "Planification et execution de la migration vers le cloud incluant l'evaluation des workloads et la gestion des couts.",
    botCode: "CTOB",
    blueprintSection: "infrastructure",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Plan de migration cloud", "Architecture cible", "Budget et economies projetees"],
    source: "existant",
  },
  {
    id: "PB-CTOB-003",
    name: "Plan de reprise apres sinistre",
    description: "Documentation et tests du plan de reprise informatique pour assurer la continuite des operations.",
    botCode: "CTOB",
    blueprintSection: "infrastructure",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Plan DRP documente", "Procedures de restauration", "Rapport de test DRP"],
    source: "existant",
  },
  {
    id: "PB-CTOB-004",
    name: "Implantation MES",
    description: "Deploiement d'un systeme d'execution de la fabrication pour la visibilite en temps reel de la production.",
    botCode: "CTOB",
    blueprintSection: "architecture_si",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-9 mois",
    deliverables: ["Cahier des charges MES", "Plan d'integration ERP-MES", "Formation operateurs"],
    source: "existant",
  },
  {
    id: "PB-CTOB-005",
    name: "Programme maintenance predictive",
    description: "Deploiement de capteurs IoT et d'algorithmes d'IA pour predire les defaillances d'equipements.",
    botCode: "CTOB",
    blueprintSection: "infrastructure",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Architecture IoT", "Modeles predictifs", "Tableau de bord maintenance"],
    source: "existant",
  },

  // -- Nouveaux CTOB (DeepSearch) --
  {
    id: "PB-CTOB-006",
    name: "Transformation numerique globale",
    description: "Planifier et executer la numerisation de bout en bout en s'appuyant sur l'OTN du gouvernement du Quebec.",
    botCode: "CTOB",
    blueprintSection: "roadmap_tech",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Audit de maturite numerique", "Feuille de route transformation", "Dossier subvention OTN"],
    source: "nouveau",
  },
  {
    id: "PB-CTOB-007",
    name: "Migration et implantation ERP",
    description: "Choix, configuration et deploiement d'un ERP adapte a la taille de l'entreprise avec gestion du changement.",
    botCode: "CTOB",
    blueprintSection: "architecture_si",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-9 mois",
    deliverables: ["Cahier des charges ERP", "Plan de migration donnees", "Formation utilisateurs"],
    source: "nouveau",
  },
  {
    id: "PB-CTOB-008",
    name: "Strategie donnees et analytics (BI)",
    description: "Mise en place d'une infrastructure de donnees et de tableaux de bord analytiques pour le pilotage.",
    botCode: "CTOB",
    blueprintSection: "architecture_si",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 mois",
    deliverables: ["Architecture donnees", "Tableaux de bord BI", "Dictionnaire de donnees"],
    source: "nouveau",
  },
  {
    id: "PB-CTOB-009",
    name: "DevOps et CI/CD",
    description: "Implantation de pipelines d'integration et de deploiement continus pour accelerer les livraisons logicielles.",
    botCode: "CTOB",
    blueprintSection: "stack_technique",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Pipeline CI/CD automatise", "Strategie de branching", "Documentation DevOps"],
    source: "nouveau",
  },
  {
    id: "PB-CTOB-010",
    name: "Industrie 4.0 — IoT et connectivite usine",
    description: "Installation de capteurs IoT sur les equipements de production pour le suivi temps reel et l'optimisation.",
    botCode: "CTOB",
    blueprintSection: "infrastructure",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Architecture IoT industrielle", "Plan de deploiement capteurs", "Tableaux de bord temps reel"],
    source: "nouveau",
  },
  {
    id: "PB-CTOB-011",
    name: "Audit et remediation de dette technique",
    description: "Evaluation systematique de la dette technique et plan de remediation priorise pour stabiliser le code.",
    botCode: "CTOB",
    blueprintSection: "dette_technique",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Rapport d'audit technique", "Score de dette", "Plan de remediation priorise"],
    source: "nouveau",
  },
  {
    id: "PB-CTOB-012",
    name: "Architecture cloud-native et microservices",
    description: "Refactorisation de l'architecture applicative vers des microservices conteneurises et scalables.",
    botCode: "CTOB",
    blueprintSection: "stack_technique",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Architecture microservices", "Plan de conteneurisation", "Strategie de deploiement"],
    source: "nouveau",
  },
  {
    id: "PB-CTOB-013",
    name: "Automatisation robotique des processus (RPA)",
    description: "Identification et automatisation des taches repetitives a haute valeur via des robots logiciels.",
    botCode: "CTOB",
    blueprintSection: "roadmap_tech",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 mois",
    deliverables: ["Inventaire processus automatisables", "Robots configures", "ROI par processus"],
    source: "nouveau",
  },

  // ============================================================
  // CFOB — Frank — Finance (3 existants + 8 nouveaux = 11)
  // ============================================================

  // -- Existants CFOB --
  {
    id: "PB-CFOB-001",
    name: "Prevision tresorerie 13 semaines",
    description: "Modele de prevision de tresorerie glissant sur 13 semaines pour anticiper les ecarts de liquidite.",
    botCode: "CFOB",
    blueprintSection: "tresorerie",
    phase: "startup",
    phases: ["startup", "scaleup", "exitup"],
    minTier: 1,
    maxTier: 5,
    complexity: "simple",
    estimatedDuration: "1-2 semaines",
    deliverables: ["Modele cash flow 13 semaines", "Alertes de seuils", "Rapport hebdomadaire tresorerie"],
    source: "existant",
  },
  {
    id: "PB-CFOB-002",
    name: "Preparation financement",
    description: "Construction d'un dossier solide pour obtenir du financement bancaire ou en capital-risque.",
    botCode: "CFOB",
    blueprintSection: "modele_revenus",
    phase: "startup",
    phases: ["startup", "scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Dossier financier complet", "Projections 3-5 ans", "Pitch deck investisseurs"],
    source: "existant",
  },
  {
    id: "PB-CFOB-003",
    name: "Due diligence financiere",
    description: "Verification approfondie des etats financiers, de la qualite des revenus et des risques fiscaux.",
    botCode: "CFOB",
    blueprintSection: "valorisation",
    phase: "exitup",
    phases: ["exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["Quality of Earnings (QoE)", "Rapport de normalisation EBITDA", "Liste des risques fiscaux"],
    source: "existant",
  },

  // -- Nouveaux CFOB (DeepSearch) --
  {
    id: "PB-CFOB-004",
    name: "Restructuration financiere et redressement",
    description: "Actions urgentes pour stabiliser la tresorerie, renegocier les dettes et restructurer les couts.",
    botCode: "CFOB",
    blueprintSection: "tresorerie",
    phase: "startup",
    phases: ["startup", "scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["Plan de restructuration", "Echeancier de renegociation", "Budget de crise"],
    source: "nouveau",
  },
  {
    id: "PB-CFOB-005",
    name: "Montage financier et recherche de financement",
    description: "Construire des dossiers solides pour acceder a des capitaux tels que les FLI ou le programme ESSOR.",
    botCode: "CFOB",
    blueprintSection: "modele_revenus",
    phase: "startup",
    phases: ["startup", "scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Dossier de financement", "Projections financieres", "Plan d'utilisation des fonds"],
    source: "nouveau",
  },
  {
    id: "PB-CFOB-006",
    name: "Controle de gestion et tableaux de bord financiers",
    description: "Mise en place de tableaux de bord financiers granulaires pour le pilotage operationnel et strategique.",
    botCode: "CFOB",
    blueprintSection: "kpis_finance",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Tableau de bord financier", "Grille de KPIs par departement", "Rapports mensuels automatises"],
    source: "nouveau",
  },
  {
    id: "PB-CFOB-007",
    name: "Gestion de tresorerie et optimisation du BFR",
    description: "Optimiser le besoin en fonds de roulement en ameliorant les delais de paiement et de recouvrement.",
    botCode: "CFOB",
    blueprintSection: "tresorerie",
    phase: "scaleup",
    phases: ["startup", "scaleup", "exitup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Analyse du cycle de conversion", "Plan d'optimisation DSO/DPO", "Modele de prevision BFR"],
    source: "nouveau",
  },
  {
    id: "PB-CFOB-008",
    name: "Optimisation fiscale et credits d'impot",
    description: "Maximiser l'utilisation des leviers fiscaux comme le credit RS&DE et les credits d'impot provinciaux.",
    botCode: "CFOB",
    blueprintSection: "fiscalite",
    phase: "scaleup",
    phases: ["startup", "scaleup", "exitup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 semaines",
    deliverables: ["Inventaire des credits admissibles", "Strategie fiscale annuelle", "Calendrier des demandes"],
    source: "nouveau",
  },
  {
    id: "PB-CFOB-009",
    name: "Budget et previsions financieres annuelles",
    description: "Processus budgetaire rigoureux avec scenarios pessimiste, realiste et optimiste.",
    botCode: "CFOB",
    blueprintSection: "budget_previsions",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Budget annuel detaille", "3 scenarios financiers", "Grille de suivi budgetaire"],
    source: "nouveau",
  },
  {
    id: "PB-CFOB-010",
    name: "Valorisation d'entreprise et modelisation",
    description: "Etablir la valeur marchande de l'entreprise via des methodes reconnues (DCF, multiples, comparables).",
    botCode: "CFOB",
    blueprintSection: "valorisation",
    phase: "exitup",
    phases: ["exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Modele de valorisation DCF", "Analyse de comparables", "Rapport de valorisation"],
    source: "nouveau",
  },
  {
    id: "PB-CFOB-011",
    name: "Reddition de comptes et subventions (OBNL)",
    description: "Standardiser la collecte des donnees d'impact social et la preparation des rapports exiges par les ministeres.",
    botCode: "CFOB",
    blueprintSection: "etats_financiers",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-6 semaines",
    deliverables: ["Gabarit de reddition", "Tableau indicateurs d'impact", "Rapport annuel conforme"],
    source: "nouveau",
  },

  // ============================================================
  // CMOB — Mathilde — Marketing (2 existants + 10 nouveaux = 12)
  // ============================================================

  // -- Existants CMOB --
  {
    id: "PB-CMOB-001",
    name: "Strategie contenu B2B",
    description: "Deploiement d'une strategie de contenu pour generer du trafic organique et des leads qualifies.",
    botCode: "CMOB",
    blueprintSection: "contenu_campagnes",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Calendrier editorial", "Grappes de contenu (topic clusters)", "Guide de style redactionnel"],
    source: "existant",
  },
  {
    id: "PB-CMOB-002",
    name: "Lancement campagne lead-gen",
    description: "Conception et deploiement d'une campagne multicanal pour generer des prospects B2B qualifies.",
    botCode: "CMOB",
    blueprintSection: "canaux_budget",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Plan de campagne", "Landing pages", "Sequences de nurturing"],
    source: "existant",
  },
  {
    id: "PB-CMOB-003",
    name: "Audit marque",
    description: "Evaluation complete du positionnement de la marque, de l'identite visuelle et de la perception client.",
    botCode: "CMOB",
    blueprintSection: "positionnement",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "simple",
    estimatedDuration: "2-3 semaines",
    deliverables: ["Rapport d'audit marque", "Matrice de perception", "Recommandations prioritaires"],
    source: "existant",
  },

  // -- Nouveaux CMOB (DeepSearch C.1) --
  {
    id: "PB-CMOB-004",
    name: "Strategie marketing et plan annuel",
    description: "Definir le positionnement, les personas cibles et l'allocation du budget numerique pour generer un flux previsible de prospects.",
    botCode: "CMOB",
    blueprintSection: "canaux_budget",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Plan marketing annuel", "Profils clients ideaux (ICP)", "Allocation budgetaire par canal"],
    source: "nouveau",
  },
  {
    id: "PB-CMOB-005",
    name: "Construction de marque et identite visuelle",
    description: "Structurer l'identite nominale et visuelle (logo, charte graphique) pour assurer une coherence sur toutes les plateformes.",
    botCode: "CMOB",
    blueprintSection: "positionnement",
    phase: "startup",
    phases: ["startup", "scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Charte graphique complete", "Guide de marque", "Kit de communication"],
    source: "nouveau",
  },
  {
    id: "PB-CMOB-006",
    name: "Marketing numerique et acquisition",
    description: "Deploiement tactique sur les canaux numeriques: Google Ads, LinkedIn Ads, optimisation du site web pour les conversions.",
    botCode: "CMOB",
    blueprintSection: "canaux_budget",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Campagnes Google Ads configurees", "Landing pages optimisees", "Rapport ROI par canal"],
    source: "nouveau",
  },
  {
    id: "PB-CMOB-007",
    name: "Strategie contenu et SEO",
    description: "Generer du trafic organique via l'audit semantique, les grappes de contenu et les techniques de referencement naturel.",
    botCode: "CMOB",
    blueprintSection: "contenu_campagnes",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "6-12 semaines",
    deliverables: ["Audit SEO complet", "Calendrier editorial 12 mois", "Grappes de contenu structurees"],
    source: "nouveau",
  },
  {
    id: "PB-CMOB-008",
    name: "Automatisation marketing (MarTech)",
    description: "Orchestrer l'integration de plateformes pour automatiser les sequences, le lead scoring et le nurturing.",
    botCode: "CMOB",
    blueprintSection: "automatisation",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Plateforme MarTech configuree", "Workflows automatises", "Grille de lead scoring"],
    source: "nouveau",
  },
  {
    id: "PB-CMOB-009",
    name: "Lancement produit — Go-to-Market",
    description: "Orchestrer la tarification, la creation de materiel promotionnel et le plan de communication pour un nouveau produit.",
    botCode: "CMOB",
    blueprintSection: "contenu_campagnes",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Plan de lancement GTM", "Kit de vente", "Calendrier de communication"],
    source: "nouveau",
  },
  {
    id: "PB-CMOB-010",
    name: "Gestion reputation et relations publiques",
    description: "Structurer la reponse aux avis en ligne, les communiques de presse cibles et les collaborations influenceurs.",
    botCode: "CMOB",
    blueprintSection: "reputation",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Politique de gestion des avis", "Kit relations medias", "Plan de communication de crise"],
    source: "nouveau",
  },
  {
    id: "PB-CMOB-011",
    name: "Programme de fidelisation et retention",
    description: "Augmenter la valeur a vie (LTV) des clients existants via des programmes ambassadeurs et des sondages de satisfaction.",
    botCode: "CMOB",
    blueprintSection: "kpis_marketing",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Programme ambassadeur", "Sondage de satisfaction", "Plan de retention"],
    source: "nouveau",
  },
  {
    id: "PB-CMOB-012",
    name: "Rebranding et repositionnement",
    description: "Intervention strategique pour les entreprises pivotant leur modele d'affaires ou integrant une acquisition.",
    botCode: "CMOB",
    blueprintSection: "positionnement",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["Nouvelle identite visuelle", "Plan de migration de marque", "Communication de transition"],
    source: "nouveau",
  },
  {
    id: "PB-CMOB-013",
    name: "Marketing B2B Account-Based (ABM)",
    description: "Aligner les ventes et le marketing pour cibler un petit nombre de comptes a haute valeur avec du contenu hyper-personnalise.",
    botCode: "CMOB",
    blueprintSection: "personas_icp",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Liste de comptes cibles ABM", "Contenu personnalise par compte", "Tableau de bord ABM"],
    source: "nouveau",
  },

  // ============================================================
  // CSOB — Simone — Strategie (2 existants + 10 nouveaux = 12)
  // ============================================================

  // -- Existants CSOB --
  {
    id: "PB-CSOB-001",
    name: "Analyse concurrentielle",
    description: "Evaluation complete du positionnement relatif, des structures de couts des rivaux et de leur part de voix.",
    botCode: "CSOB",
    blueprintSection: "concurrence",
    phase: "scaleup",
    phases: ["startup", "scaleup", "exitup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 semaines",
    deliverables: ["Matrice concurrentielle", "Analyse de part de voix", "Recommandations strategiques"],
    source: "existant",
  },
  {
    id: "PB-CSOB-002",
    name: "Plan d'expansion de marche",
    description: "Evaluation et planification de la penetration de nouveaux marches geographiques ou sectoriels.",
    botCode: "CSOB",
    blueprintSection: "diversification",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["Analyse TAM/SAM/SOM", "Plan d'entree par marche", "Budget d'expansion"],
    source: "existant",
  },
  {
    id: "PB-CSOB-003",
    name: "Preparation M&A",
    description: "Guide d'identification de cibles d'acquisition, d'evaluation des synergies et de lettres d'intention.",
    botCode: "CSOB",
    blueprintSection: "diversification",
    phase: "exitup",
    phases: ["scaleup", "exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Liste de cibles evaluees", "Modele de synergies", "Lettre d'intention (LOI)"],
    source: "existant",
  },

  // -- Nouveaux CSOB (DeepSearch C.3) --
  {
    id: "PB-CSOB-004",
    name: "Planification strategique 3-5 ans",
    description: "Structurer la vision a long terme via l'analyse des capacites internes et la creation d'un plan d'action mesurable.",
    botCode: "CSOB",
    blueprintSection: "pestel",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-3 mois",
    deliverables: ["Plan strategique 3-5 ans", "Axes directeurs", "Feuille de route annuelle"],
    source: "nouveau",
  },
  {
    id: "PB-CSOB-005",
    name: "Veille strategique et intelligence de marche",
    description: "Mise en place d'outils automatises pour surveiller la concurrence, les evolutions reglementaires et les tendances.",
    botCode: "CSOB",
    blueprintSection: "concurrence",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-4 semaines",
    deliverables: ["Systeme de veille configure", "Rapports trimestriels PESTEL", "Alertes concurrentielles"],
    source: "nouveau",
  },
  {
    id: "PB-CSOB-006",
    name: "Analyse concurrentielle approfondie",
    description: "Deploiement d'un cadre d'analyse rigoureux pour evaluer le positionnement relatif et les structures de couts.",
    botCode: "CSOB",
    blueprintSection: "concurrence",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Matrice concurrentielle detaillee", "Analyse de la chaine de valeur", "Rapport de benchmarking"],
    source: "nouveau",
  },
  {
    id: "PB-CSOB-007",
    name: "Diversification et penetration de nouveaux marches",
    description: "Evaluation du TAM/SAM/SOM pour valider financierement l'entree dans une nouvelle verticalite.",
    botCode: "CSOB",
    blueprintSection: "marche",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["Etude de marche cible", "Analyse TAM/SAM/SOM", "Business case d'entree"],
    source: "nouveau",
  },
  {
    id: "PB-CSOB-008",
    name: "Partenariats strategiques et alliances",
    description: "Cadre d'evaluation pour forger des alliances tactiques, co-developpement ou consortiums de R&D.",
    botCode: "CSOB",
    blueprintSection: "partenariats",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Grille d'evaluation partenaires", "Modele d'entente", "Plan de co-developpement"],
    source: "nouveau",
  },
  {
    id: "PB-CSOB-009",
    name: "Strategie M&A et croissance externe",
    description: "Identification de cibles d'acquisition, evaluation des synergies et structuration des transactions.",
    botCode: "CSOB",
    blueprintSection: "diversification",
    phase: "exitup",
    phases: ["scaleup", "exitup"],
    minTier: 4,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Pipeline de cibles M&A", "Modele de synergies", "Structure de transaction"],
    source: "nouveau",
  },
  {
    id: "PB-CSOB-010",
    name: "Etude de marche et faisabilite",
    description: "Collecte de donnees primaires (sondages, entrevues) pour reduire le risque avant un investissement majeur.",
    botCode: "CSOB",
    blueprintSection: "marche",
    phase: "startup",
    phases: ["startup", "scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Rapport d'etude de marche", "Sondage quantitatif", "Analyse de faisabilite"],
    source: "nouveau",
  },
  {
    id: "PB-CSOB-011",
    name: "Avantages concurrentiels et moats",
    description: "Consolider les barrieres a l'entree: propriete intellectuelle, effets de reseau, securisation approvisionnement.",
    botCode: "CSOB",
    blueprintSection: "avantage_concurrentiel",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Inventaire des moats", "Plan de renforcement PI", "Strategie d'effets de reseau"],
    source: "nouveau",
  },
  {
    id: "PB-CSOB-012",
    name: "Exportation et strategie internationale",
    description: "Guider les entreprises matures vers les marches exterieurs en s'appuyant sur les programmes gouvernementaux.",
    botCode: "CSOB",
    blueprintSection: "diversification",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Plan d'exportation", "Dossier Panorama IQ", "Etude de marche pays cible"],
    source: "nouveau",
  },
  {
    id: "PB-CSOB-013",
    name: "Transformation et pivot du modele d'affaires",
    description: "Accompagner le changement fondamental de la maniere dont la PME cree de la valeur (ex: produit vers SaaS).",
    botCode: "CSOB",
    blueprintSection: "pestel",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Nouveau Business Model Canvas", "Plan de transition", "Projections financieres du pivot"],
    source: "nouveau",
  },

  // ============================================================
  // COOB — Olivier — Operations (5 existants + 6 nouveaux = 11)
  // ============================================================

  // -- Existants COOB --
  {
    id: "PB-COOB-001",
    name: "Cartographie des processus",
    description: "Cartographie complete des processus d'affaires cles pour identifier les goulots et les inefficacites.",
    botCode: "COOB",
    blueprintSection: "processus",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Cartographie BPMN des processus", "Matrice des goulots", "Plan d'optimisation priorise"],
    source: "existant",
  },
  {
    id: "PB-COOB-002",
    name: "Audit supply chain",
    description: "Evaluation complete de la chaine d'approvisionnement incluant fournisseurs, lead times et risques.",
    botCode: "COOB",
    blueprintSection: "supply_chain",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-4 semaines",
    deliverables: ["Rapport d'audit supply chain", "Matrice des risques", "Plan B fournisseurs"],
    source: "existant",
  },
  {
    id: "PB-COOB-003",
    name: "Programme 5S",
    description: "Deploiement systematique du 5S (Seiri, Seiton, Seiso, Seiketsu, Shitsuke) pour l'organisation du lieu de travail.",
    botCode: "COOB",
    blueprintSection: "amelioration_continue",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "simple",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Grille d'audit 5S", "Photos avant/apres", "Standards visuels"],
    source: "existant",
  },
  {
    id: "PB-COOB-004",
    name: "Optimisation chaine d'approvisionnement",
    description: "Optimisation des flux physiques et d'information pour ameliorer la productivite et reduire les couts logistiques.",
    botCode: "COOB",
    blueprintSection: "supply_chain",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Plan d'optimisation supply chain", "Indicateurs OTIF", "Strategie S&OP"],
    source: "existant",
  },
  {
    id: "PB-COOB-005",
    name: "Certification qualite (ISO 9001, 13485)",
    description: "Deploiement du systeme de management de la qualite conforme aux normes internationales.",
    botCode: "COOB",
    blueprintSection: "amelioration_continue",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Manuel qualite", "Procedures documentees", "Rapport de pre-audit"],
    source: "existant",
  },

  // -- Nouveaux COOB (DeepSearch B.6) --
  {
    id: "PB-COOB-006",
    name: "Cartographie et optimisation des processus (BPM)",
    description: "Modelisation et optimisation des processus d'affaires cles selon la methodologie BPM.",
    botCode: "COOB",
    blueprintSection: "processus",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Modeles BPMN", "Analyse de valeur ajoutee", "Plan de redesign"],
    source: "nouveau",
  },
  {
    id: "PB-COOB-007",
    name: "Lean Six Sigma — Programme DMAIC",
    description: "Deployer la methodologie DMAIC pour reduire la variabilite et les gaspillages dans les processus.",
    botCode: "COOB",
    blueprintSection: "amelioration_continue",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Charte de projet DMAIC", "Analyse OEE/TRS", "Plans de controle statistique"],
    source: "nouveau",
  },
  {
    id: "PB-COOB-008",
    name: "Gestion de la chaine d'approvisionnement (S&OP)",
    description: "Processus de planification des ventes et operations pour equilibrer offre et demande.",
    botCode: "COOB",
    blueprintSection: "supply_chain",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["Processus S&OP documente", "Previsions de demande", "Plan d'approvisionnement"],
    source: "nouveau",
  },
  {
    id: "PB-COOB-009",
    name: "Programme qualite ISO 9001",
    description: "Deploiement complet d'un systeme de management qualite conforme ISO 9001:2015.",
    botCode: "COOB",
    blueprintSection: "amelioration_continue",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Manuel qualite ISO", "Procedures obligatoires", "Plan d'audit interne"],
    source: "nouveau",
  },
  {
    id: "PB-COOB-010",
    name: "Gestion des fournisseurs et achats strategiques",
    description: "Structurer l'evaluation des fournisseurs, les SLA et les strategies d'achat pour securiser l'approvisionnement.",
    botCode: "COOB",
    blueprintSection: "gestion_fournisseurs",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Grille d'evaluation fournisseurs", "SLA standardises", "Strategie d'achat par categorie"],
    source: "nouveau",
  },
  {
    id: "PB-COOB-011",
    name: "Optimisation de l'entreposage et gestion WMS",
    description: "Implantation d'un systeme de gestion d'entrepot pour maximiser la productivite logistique.",
    botCode: "COOB",
    blueprintSection: "logistique",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Cahier des charges WMS", "Optimisation layout entrepot", "Formation preparateurs"],
    source: "nouveau",
  },

  // ============================================================
  // CPOB — Paco — Production (3 existants + 7 nouveaux = 10)
  // ============================================================

  // -- Existants CPOB --
  {
    id: "PB-CPOB-001",
    name: "Programme prevention SST",
    description: "Etablissement d'un programme de prevention en sante et securite au travail conforme CNESST.",
    botCode: "CPOB",
    blueprintSection: "sst",
    phase: "scaleup",
    phases: ["startup", "scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Programme de prevention SST", "Registre des dangers", "Plan de formation SST"],
    source: "existant",
  },
  {
    id: "PB-CPOB-002",
    name: "Audit qualite interne",
    description: "Processus d'audit interne pour evaluer la conformite du systeme qualite et identifier les ameliorations.",
    botCode: "CPOB",
    blueprintSection: "qualite",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 semaines",
    deliverables: ["Plan d'audit annuel", "Rapport d'audit", "Plan d'actions correctives"],
    source: "existant",
  },
  {
    id: "PB-CPOB-003",
    name: "Programme maintenance preventive",
    description: "Mise en place d'un programme de maintenance preventive systematique pour maximiser la disponibilite.",
    botCode: "CPOB",
    blueprintSection: "equipements",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Calendrier de maintenance", "Fiches d'equipement", "Indicateurs MTBF/MTTR"],
    source: "existant",
  },

  // -- Nouveaux CPOB (DeepSearch B.7) --
  {
    id: "PB-CPOB-004",
    name: "Conception et mise en service d'une ligne automatisee",
    description: "Conception, installation et mise en production d'une ligne de fabrication automatisee.",
    botCode: "CPOB",
    blueprintSection: "equipements",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Cahier des charges ligne", "Plan d'implantation", "Protocole de mise en service"],
    source: "nouveau",
  },
  {
    id: "PB-CPOB-005",
    name: "Certification IATF 16949 (automobile)",
    description: "Obtenir la norme de gestion de la qualite essentielle pour les fournisseurs de l'industrie automobile.",
    botCode: "CPOB",
    blueprintSection: "normes_certifications",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Manuel qualite IATF", "Plans APQP/PPAP", "Analyses FMEA"],
    source: "nouveau",
  },
  {
    id: "PB-CPOB-006",
    name: "Tracabilite complete de lot",
    description: "Implantation d'un systeme de tracabilite de lot complet pour l'industrie agroalimentaire ou manufacturiere.",
    botCode: "CPOB",
    blueprintSection: "qualite",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Systeme de tracabilite", "Procedures de rappel", "Tests de tracabilite"],
    source: "nouveau",
  },
  {
    id: "PB-CPOB-007",
    name: "Programme de reduction des rebuts et non-conformites",
    description: "Analyse des causes racines et actions correctives pour reduire le taux de rejet et les couts de non-qualite.",
    botCode: "CPOB",
    blueprintSection: "qualite",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 mois",
    deliverables: ["Analyse Pareto des rebuts", "Plans 8D par probleme", "Indicateurs qualite ameliores"],
    source: "nouveau",
  },
  {
    id: "PB-CPOB-008",
    name: "Planification de la production et ordonnancement",
    description: "Structurer la planification de la production pour optimiser les capacites et respecter les delais.",
    botCode: "CPOB",
    blueprintSection: "planification_production",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Plan directeur de production", "Ordonnancement optimise", "Indicateurs de charge/capacite"],
    source: "nouveau",
  },
  {
    id: "PB-CPOB-009",
    name: "Robotisation et cellule de travail automatisee",
    description: "Integration de robots industriels dans les cellules de production pour augmenter la productivite.",
    botCode: "CPOB",
    blueprintSection: "equipements",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Etude de faisabilite robotique", "Analyse de ROI", "Plan d'integration"],
    source: "nouveau",
  },
  {
    id: "PB-CPOB-010",
    name: "Gestion des stocks et inventaire perpetuel",
    description: "Mise en place d'un systeme d'inventaire perpetuel avec niveaux min/max automatises.",
    botCode: "CPOB",
    blueprintSection: "gestion_stocks",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Systeme d'inventaire perpetuel", "Niveaux min/max par SKU", "Rapport de rotation stocks"],
    source: "nouveau",
  },

  // ============================================================
  // CHROB — Helene — Ressources Humaines (3 existants + 7 nouveaux = 10)
  // ============================================================

  // -- Existants CHROB --
  {
    id: "PB-CHROB-001",
    name: "Exercice d'equite salariale",
    description: "Realisation de l'exercice d'equite salariale conforme a la Loi sur l'equite salariale de la CNESST.",
    botCode: "CHROB",
    blueprintSection: "conformite_rh",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Exercice d'equite salariale", "Rapport de maintien", "Affichage obligatoire"],
    source: "existant",
  },
  {
    id: "PB-CHROB-002",
    name: "Programme d'onboarding",
    description: "Conception d'un programme d'accueil structure pour les nouveaux employes couvrant les 90 premiers jours.",
    botCode: "CHROB",
    blueprintSection: "recrutement",
    phase: "scaleup",
    phases: ["startup", "scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "simple",
    estimatedDuration: "2-4 semaines",
    deliverables: ["Kit d'accueil", "Plan d'integration 90 jours", "Checklist d'onboarding"],
    source: "existant",
  },
  {
    id: "PB-CHROB-003",
    name: "Plan de succession et gestion des talents",
    description: "Identification des postes cles et des hauts potentiels avec plans de developpement individualises.",
    botCode: "CHROB",
    blueprintSection: "succession",
    phase: "exitup",
    phases: ["scaleup", "exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Matrice 9-box", "Plans de developpement individuels", "Plan de succession"],
    source: "existant",
  },

  // -- Nouveaux CHROB (DeepSearch B.8) --
  {
    id: "PB-CHROB-004",
    name: "Plan de recrutement massif et strategie de talent",
    description: "Soutenir l'hypercroissance avec un processus de recrutement structure et une marque employeur forte.",
    botCode: "CHROB",
    blueprintSection: "recrutement",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["Strategie de recrutement", "Pipeline de candidats", "Marque employeur deployee"],
    source: "nouveau",
  },
  {
    id: "PB-CHROB-005",
    name: "Programme de formation et developpement des competences",
    description: "Structurer le developpement professionnel avec des plans de formation alignes sur la strategie.",
    botCode: "CHROB",
    blueprintSection: "formation",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Plan de formation annuel", "Matrice des competences", "Budget formation (Loi 90)"],
    source: "nouveau",
  },
  {
    id: "PB-CHROB-006",
    name: "Politique de remuneration et equite salariale",
    description: "Se conformer aux exigences de la Loi sur l'equite salariale en evaluant et maintenant l'equite.",
    botCode: "CHROB",
    blueprintSection: "remuneration",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Grille salariale", "Exercice d'equite salariale", "Politique de remuneration"],
    source: "nouveau",
  },
  {
    id: "PB-CHROB-007",
    name: "Sondage engagement et plan d'amelioration du climat",
    description: "Mesurer l'engagement des employes et deployer un plan d'amelioration du climat organisationnel.",
    botCode: "CHROB",
    blueprintSection: "culture_engagement",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Sondage engagement deploye", "Rapport d'analyse", "Plan d'action par equipe"],
    source: "nouveau",
  },
  {
    id: "PB-CHROB-008",
    name: "Plan de succession et gestion des talents cles",
    description: "Verrouiller le personnel cle avec des plans de retention et identifier les successeurs potentiels.",
    botCode: "CHROB",
    blueprintSection: "succession",
    phase: "exitup",
    phases: ["exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Plan de succession detaille", "Ententes de retention (Golden Handcuffs)", "Programme de mentorat"],
    source: "nouveau",
  },
  {
    id: "PB-CHROB-009",
    name: "Conformite normes du travail et sante-securite",
    description: "Etablir un programme de prevention conforme aux exigences de la CNESST pour un milieu de travail sain.",
    botCode: "CHROB",
    blueprintSection: "conformite_rh",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Programme de prevention", "Registre des incidents", "Formation SST employes"],
    source: "nouveau",
  },
  {
    id: "PB-CHROB-010",
    name: "Programme de bien-etre et sante mentale au travail",
    description: "Deployer un programme de soutien a la sante mentale et au bien-etre des employes.",
    botCode: "CHROB",
    blueprintSection: "culture_engagement",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Programme PAE", "Politique sante mentale", "Formation gestionnaires"],
    source: "nouveau",
  },

  // ============================================================
  // CINOB — Ines — Innovation & R&D (2 existants + 7 nouveaux = 9)
  // ============================================================

  // -- Existants CINOB --
  {
    id: "PB-CINOB-001",
    name: "Programme RS&DE",
    description: "Structuration de la R&D pour documenter l'avancement technologique et maximiser les credits d'impot RS&DE.",
    botCode: "CINOB",
    blueprintSection: "rsde",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Documentation RS&DE", "Feuilles de temps R&D", "Demande de credit"],
    source: "existant",
  },
  {
    id: "PB-CINOB-002",
    name: "Processus d'innovation Stage-Gate",
    description: "Mise en place d'un processus structure de gestion de l'innovation avec des portes de decision.",
    botCode: "CINOB",
    blueprintSection: "pipeline_innovation",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Processus Stage-Gate documente", "Grilles d'evaluation par porte", "Tableau Kanban innovation"],
    source: "existant",
  },
  {
    id: "PB-CINOB-003",
    name: "Veille technologique",
    description: "Systeme de veille structure pour surveiller les tendances technologiques et identifier les opportunites.",
    botCode: "CINOB",
    blueprintSection: "veille",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "simple",
    estimatedDuration: "2-3 semaines",
    deliverables: ["Sources de veille configurees", "Rapports trimestriels", "Alertes automatisees"],
    source: "existant",
  },
  {
    id: "PB-CINOB-004",
    name: "Programme d'innovation ouverte",
    description: "Stimuler l'innovation par des partenariats externes, hackathons et intrapreneuriat.",
    botCode: "CINOB",
    blueprintSection: "pipeline_innovation",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 mois",
    deliverables: ["Programme d'intrapreneuriat", "Cadre de partenariat ouvert", "Tableau des idees"],
    source: "existant",
  },

  // -- Nouveaux CINOB (DeepSearch B.9) --
  {
    id: "PB-CINOB-005",
    name: "Programme de R&D structure et credits RS&DE",
    description: "Structurer la R&D pour documenter l'avancement technologique et repondre aux criteres du programme RS&DE.",
    botCode: "CINOB",
    blueprintSection: "rsde",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Registre de projets R&D", "Documentation technique RS&DE", "Calcul du credit remboursable"],
    source: "nouveau",
  },
  {
    id: "PB-CINOB-006",
    name: "Developpement de nouveaux produits (NPD)",
    description: "Processus structure de developpement de produits de l'idee au lancement commercial.",
    botCode: "CINOB",
    blueprintSection: "pipeline_innovation",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-9 mois",
    deliverables: ["Cahier des charges produit", "Prototype valide", "Plan de lancement"],
    source: "nouveau",
  },
  {
    id: "PB-CINOB-007",
    name: "Programme de gestion de la propriete intellectuelle",
    description: "Identifier, proteger et valoriser les actifs de propriete intellectuelle de l'entreprise.",
    botCode: "CINOB",
    blueprintSection: "propriete_intellectuelle",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Inventaire PI", "Strategie de brevets", "Politique de PI interne"],
    source: "nouveau",
  },
  {
    id: "PB-CINOB-008",
    name: "Veille technologique et programme d'innovation ouverte",
    description: "Systeme de veille avancee couple a des initiatives d'innovation ouverte avec partenaires externes.",
    botCode: "CINOB",
    blueprintSection: "veille",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Plateforme de veille configuree", "Programme hackathon", "Rapport tendances"],
    source: "nouveau",
  },
  {
    id: "PB-CINOB-009",
    name: "Processus de prototypage rapide et MVP",
    description: "Mettre en place un processus de prototypage rapide pour valider les concepts avant investissement.",
    botCode: "CINOB",
    blueprintSection: "prototypage",
    phase: "startup",
    phases: ["startup", "scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-6 semaines",
    deliverables: ["Prototype fonctionnel", "Resultats tests utilisateurs", "Go/No-Go decision"],
    source: "nouveau",
  },
  {
    id: "PB-CINOB-010",
    name: "Partenariats de recherche universitaire",
    description: "Etablir des collaborations avec des universites et centres de recherche via des programmes comme MITACS.",
    botCode: "CINOB",
    blueprintSection: "partenariats_rd",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Entente de collaboration", "Dossier MITACS", "Plan de recherche conjoint"],
    source: "nouveau",
  },
  {
    id: "PB-CINOB-011",
    name: "Programme d'intrapreneuriat et culture d'innovation",
    description: "Creer une culture ou les employes peuvent proposer, developper et tester de nouvelles idees.",
    botCode: "CINOB",
    blueprintSection: "pipeline_innovation",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 mois",
    deliverables: ["Programme d'intrapreneuriat", "Processus d'ideation", "Budget innovation employes"],
    source: "nouveau",
  },

  // ============================================================
  // CROB — Rich — Ventes & Revenus (2 existants + 10 nouveaux = 12)
  // ============================================================

  // -- Existants CROB --
  {
    id: "PB-CROB-001",
    name: "Processus de vente B2B",
    description: "Standardiser les etapes de qualification, la decouverte des besoins et les techniques de cloture.",
    botCode: "CROB",
    blueprintSection: "methodologie_vente",
    phase: "scaleup",
    phases: ["startup", "scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Processus de vente documente", "Scripts de qualification", "Playbook de cloture"],
    source: "existant",
  },
  {
    id: "PB-CROB-002",
    name: "Programme de comptes cles (KAM)",
    description: "Deployer des revues d'affaires trimestrielles et une cartographie des parties prenantes pour les comptes majeurs.",
    botCode: "CROB",
    blueprintSection: "comptes_cles",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Plan de compte detaille", "Template QBR", "Cartographie decision-makers"],
    source: "existant",
  },
  {
    id: "PB-CROB-003",
    name: "Optimisation pipeline",
    description: "Nettoyer, structurer et optimiser le pipeline de ventes pour ameliorer le taux de conversion.",
    botCode: "CROB",
    blueprintSection: "pipeline_funnel",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "simple",
    estimatedDuration: "2-4 semaines",
    deliverables: ["Pipeline nettoye", "Criteres de qualification", "Tableau de bord pipeline"],
    source: "existant",
  },

  // -- Nouveaux CROB (DeepSearch C.2) --
  {
    id: "PB-CROB-004",
    name: "Mise en place d'un processus de vente structure",
    description: "Standardiser les etapes de qualification et developper une approche de vente consultative B2B.",
    botCode: "CROB",
    blueprintSection: "methodologie_vente",
    phase: "scaleup",
    phases: ["startup", "scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Methodologie de vente consultative", "Scripts de decouverte", "Grille de qualification"],
    source: "nouveau",
  },
  {
    id: "PB-CROB-005",
    name: "Implantation CRM et gestion du pipeline",
    description: "Transition des fichiers Excel vers un CRM centralise avec des flux de travail automatises.",
    botCode: "CROB",
    blueprintSection: "pipeline_funnel",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["CRM configure", "Donnees migrees", "Formation equipe commerciale"],
    source: "nouveau",
  },
  {
    id: "PB-CROB-006",
    name: "Strategie de prix et politique commerciale",
    description: "Definition des grilles tarifaires, des escomptes de volume et integration d'outils CPQ.",
    botCode: "CROB",
    blueprintSection: "methodologie_vente",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Grille tarifaire", "Politique d'escompte", "Outil CPQ configure"],
    source: "nouveau",
  },
  {
    id: "PB-CROB-007",
    name: "Structuration equipe de ventes et territoires",
    description: "Division des roles (SDR, AE, CSM), attribution des quotas et des territoires geographiques.",
    botCode: "CROB",
    blueprintSection: "territoires",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Organigramme commercial", "Decoupage territorial", "Quotas par vendeur"],
    source: "nouveau",
  },
  {
    id: "PB-CROB-008",
    name: "Formation et coaching equipe commerciale",
    description: "Integrer l'ecoute d'appels, l'analyse par IA et les sessions de jeux de role pour affiner le discours.",
    botCode: "CROB",
    blueprintSection: "methodologie_vente",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Programme de coaching", "Grille d'evaluation d'appels", "Plan de montee en competences"],
    source: "nouveau",
  },
  {
    id: "PB-CROB-009",
    name: "Plan de compensation et incentifs ventes",
    description: "Definir la structure de remuneration optimale pour aligner les comportements sur les objectifs.",
    botCode: "CROB",
    blueprintSection: "remuneration_ventes",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Plan de compensation", "Grille de commissions", "Simulateur OTE"],
    source: "nouveau",
  },
  {
    id: "PB-CROB-010",
    name: "Retention et expansion clients",
    description: "Encadrer les pratiques de fidelisation pour maintenir un faible taux de desabonnement et favoriser le cross-sell.",
    botCode: "CROB",
    blueprintSection: "comptes_cles",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Programme de fidelisation", "Playbook cross-sell/upsell", "Indicateurs churn"],
    source: "nouveau",
  },
  {
    id: "PB-CROB-011",
    name: "Previsions de ventes et forecasting",
    description: "Etablir des regles strictes de mise a jour du CRM pour fournir une visibilite fiable sur les revenus a venir.",
    botCode: "CROB",
    blueprintSection: "kpis_ventes",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 semaines",
    deliverables: ["Processus de forecasting", "Regles de mise a jour pipeline", "Rapport previsionnel"],
    source: "nouveau",
  },
  {
    id: "PB-CROB-012",
    name: "Canaux indirects et programme revendeurs",
    description: "Creer un reseau de distribution externe incluant la gestion des marges partenaires et les portails revendeurs.",
    botCode: "CROB",
    blueprintSection: "pipeline_funnel",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["Programme partenaires", "Portail revendeurs", "Politique de marges"],
    source: "nouveau",
  },

  // ============================================================
  // CLOB — Loulou — Legal (3 existants + 7 nouveaux = 10)
  // ============================================================

  // -- Existants CLOB --
  {
    id: "PB-CLOB-001",
    name: "Conformite Loi 25",
    description: "Programme complet de conformite a la Loi 25 sur la protection des renseignements personnels.",
    botCode: "CLOB",
    blueprintSection: "conformite_loi25",
    phase: "scaleup",
    phases: ["startup", "scaleup", "exitup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Politique de confidentialite", "Inventaire des renseignements", "Registre des incidents"],
    source: "existant",
  },
  {
    id: "PB-CLOB-002",
    name: "Revision contrats",
    description: "Audit et mise a jour de l'ensemble des contrats clients, fournisseurs et baux.",
    botCode: "CLOB",
    blueprintSection: "contrats",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Contrats mis a jour", "Templates standardises", "Registre centralise"],
    source: "existant",
  },
  {
    id: "PB-CLOB-003",
    name: "Protection de la propriete intellectuelle",
    description: "Strategie de protection des marques, brevets et secrets commerciaux de l'entreprise.",
    botCode: "CLOB",
    blueprintSection: "pi_marques",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Inventaire PI", "Demandes de brevets/marques", "Accords de confidentialite"],
    source: "existant",
  },

  // -- Nouveaux CLOB (DeepSearch B.11) --
  {
    id: "PB-CLOB-004",
    name: "Programme de gestion contractuelle",
    description: "Deployer un systeme de gestion du cycle de vie des contrats avec alertes d'echeance.",
    botCode: "CLOB",
    blueprintSection: "contrats",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-6 semaines",
    deliverables: ["Registre centralise des contrats", "Templates par type", "Systeme d'alertes"],
    source: "nouveau",
  },
  {
    id: "PB-CLOB-005",
    name: "Conformite reglementaire sectorielle",
    description: "Identifier et respecter les obligations reglementaires specifiques au secteur d'activite.",
    botCode: "CLOB",
    blueprintSection: "reglementaire",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Inventaire des obligations", "Plan de mise en conformite", "Calendrier reglementaire"],
    source: "nouveau",
  },
  {
    id: "PB-CLOB-006",
    name: "Gouvernance corporative et pacte d'actionnaires",
    description: "Clarifier les roles des administrateurs et structurer les reglements generaux et la convention d'actionnaires.",
    botCode: "CLOB",
    blueprintSection: "structure_corporative",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Convention d'actionnaires", "Reglements generaux", "Charte du CA"],
    source: "nouveau",
  },
  {
    id: "PB-CLOB-007",
    name: "Due diligence juridique (acquisition ou vente)",
    description: "Organisation de la data room juridique et verification exhaustive des dossiers legaux.",
    botCode: "CLOB",
    blueprintSection: "litiges",
    phase: "exitup",
    phases: ["exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["Data room juridique", "Rapport de due diligence", "Liste des risques legaux"],
    source: "nouveau",
  },
  {
    id: "PB-CLOB-008",
    name: "Gestion des litiges et disputes commerciales",
    description: "Structurer la gestion proactive des litiges incluant la mediation, l'arbitrage et le suivi.",
    botCode: "CLOB",
    blueprintSection: "litiges",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-6 semaines",
    deliverables: ["Politique de gestion des litiges", "Protocole de mediation", "Registre des litiges"],
    source: "nouveau",
  },
  {
    id: "PB-CLOB-009",
    name: "Conformite droit du travail et politiques RH",
    description: "S'assurer que toutes les politiques RH respectent la Loi sur les normes du travail et les reglements provinciaux.",
    botCode: "CLOB",
    blueprintSection: "reglementaire",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Audit de conformite RH", "Politiques mises a jour", "Formation gestionnaires"],
    source: "nouveau",
  },
  {
    id: "PB-CLOB-010",
    name: "Gouvernance OBNL et Loi sur les compagnies",
    description: "Structurer le conseil d'administration et la tenue des livres pour les organismes a but non lucratif.",
    botCode: "CLOB",
    blueprintSection: "structure_corporative",
    phase: "scaleup",
    phases: ["startup", "scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Reglements generaux OBNL", "Livre des proces-verbaux", "Calendrier des obligations"],
    source: "nouveau",
  },

  // ============================================================
  // CISOB — Sebastien — Securite (2 existants + 10 nouveaux = 12)
  // ============================================================

  // -- Existants CISOB --
  {
    id: "PB-CISOB-001",
    name: "Audit securite baseline",
    description: "Evaluation de base de la posture de securite informatique pour identifier les lacunes critiques.",
    botCode: "CISOB",
    blueprintSection: "vulnerabilites",
    phase: "scaleup",
    phases: ["startup", "scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "2-4 semaines",
    deliverables: ["Rapport d'audit baseline", "Score de maturite", "Plan de remediation priorise"],
    source: "existant",
  },
  {
    id: "PB-CISOB-002",
    name: "Plan de reponse aux incidents",
    description: "Documentation du plan de reponse aux incidents de securite incluant les roles et les procedures.",
    botCode: "CISOB",
    blueprintSection: "incidents_reponse",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Plan de reponse aux incidents", "Fiches reflexes", "Test de simulation"],
    source: "existant",
  },
  {
    id: "PB-CISOB-003",
    name: "Programme de sensibilisation securite",
    description: "Campagnes de formation et de sensibilisation a la cybersecurite pour tous les employes.",
    botCode: "CISOB",
    blueprintSection: "formation_phishing",
    phase: "scaleup",
    phases: ["startup", "scaleup"],
    minTier: 1,
    maxTier: 5,
    complexity: "simple",
    estimatedDuration: "2-4 semaines",
    deliverables: ["Modules de formation", "Quiz de validation", "Politique d'hygiene numerique"],
    source: "existant",
  },
  {
    id: "PB-CISOB-004",
    name: "Programme de cybersecurite",
    description: "Deploiement d'un programme complet de cybersecurite aligne sur un framework reconnu (NIST, CIS).",
    botCode: "CISOB",
    blueprintSection: "politiques_iam",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Politique de securite", "Architecture de securite", "Score NIST"],
    source: "existant",
  },

  // -- Nouveaux CISOB (DeepSearch C.4) --
  {
    id: "PB-CISOB-005",
    name: "Plan de continuite et reprise apres sinistre (PCA/PRA)",
    description: "Garantir la resilience de l'organisation en etablissant des protocoles de maintien des fonctions critiques.",
    botCode: "CISOB",
    blueprintSection: "sauvegardes",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["PCA/PRA documente", "Matrice de criticite", "Test de restauration valide"],
    source: "nouveau",
  },
  {
    id: "PB-CISOB-006",
    name: "Gestion des identites et acces (IAM)",
    description: "Deploiement de l'authentification multifacteur, du principe du moindre privilege et des protocoles d'onboarding/offboarding.",
    botCode: "CISOB",
    blueprintSection: "politiques_iam",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Politique IAM", "MFA deploye", "Procedures onboarding/offboarding securisees"],
    source: "nouveau",
  },
  {
    id: "PB-CISOB-007",
    name: "Sensibilisation et simulation phishing",
    description: "Campagnes regulieres de faux courriels d'hameconnage couplees a des modules de formation obligatoires.",
    botCode: "CISOB",
    blueprintSection: "formation_phishing",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "simple",
    estimatedDuration: "2-4 semaines",
    deliverables: ["Simulations phishing deployees", "Rapport de score de vigilance", "Formation corrective"],
    source: "nouveau",
  },
  {
    id: "PB-CISOB-008",
    name: "Patch management et gestion des vulnerabilites",
    description: "Processus recurrent de scans de vulnerabilites et d'application systematique des correctifs de securite.",
    botCode: "CISOB",
    blueprintSection: "vulnerabilites",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-4 semaines",
    deliverables: ["Politique de patching", "Scans automatises configures", "SLA de remediation par severite"],
    source: "nouveau",
  },
  {
    id: "PB-CISOB-009",
    name: "Plan de reponse aux incidents de securite",
    description: "Definir qui fait quoi lors d'une breche incluant les obligations de signalement exigees par la Loi 25.",
    botCode: "CISOB",
    blueprintSection: "incidents_reponse",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "3-6 semaines",
    deliverables: ["Plan de reponse detaille", "Arbre de decision", "Formulaires de notification"],
    source: "nouveau",
  },
  {
    id: "PB-CISOB-010",
    name: "Certification SOC 2 Type II",
    description: "Obtenir un rapport SOC 2 Type II prouvant le maintien de controles stricts sur la securite et la confidentialite.",
    botCode: "CISOB",
    blueprintSection: "certifications_securite",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "6-12 mois",
    deliverables: ["Politiques SOC 2", "Outils de collecte de preuves", "Rapport SOC 2 Type II"],
    source: "nouveau",
  },
  {
    id: "PB-CISOB-011",
    name: "Securite cloud et protection des donnees",
    description: "Securiser les environnements infonuagiques avec chiffrement, CSPM et prevention des expositions accidentelles.",
    botCode: "CISOB",
    blueprintSection: "vulnerabilites",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "moyen",
    estimatedDuration: "4-8 semaines",
    deliverables: ["Politique securite cloud", "Configuration CSPM", "Rapport de conformite cloud"],
    source: "nouveau",
  },
  {
    id: "PB-CISOB-012",
    name: "Tests de penetration et audit securite",
    description: "Exercice d'audit ou des hackers ethiques tentent de s'introduire dans les systemes pour identifier les failles.",
    botCode: "CISOB",
    blueprintSection: "vulnerabilites",
    phase: "scaleup",
    phases: ["scaleup", "exitup"],
    minTier: 3,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-6 semaines",
    deliverables: ["Rapport de pentest", "Liste des vulnerabilites", "Plan de remediation priorise"],
    source: "nouveau",
  },
  {
    id: "PB-CISOB-013",
    name: "Architecture Zero Trust",
    description: "Repenser la securite reseau en exigeant une verification stricte et continue de chaque demande d'acces.",
    botCode: "CISOB",
    blueprintSection: "politiques_iam",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 4,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "3-6 mois",
    deliverables: ["Architecture Zero Trust", "Politique de micro-segmentation", "Plan de migration"],
    source: "nouveau",
  },
  {
    id: "PB-CISOB-014",
    name: "Conformite PCI-DSS",
    description: "Assurer la conformite aux standards de l'industrie des paiements pour les entreprises manipulant des cartes de credit.",
    botCode: "CISOB",
    blueprintSection: "certifications_securite",
    phase: "scaleup",
    phases: ["scaleup"],
    minTier: 2,
    maxTier: 5,
    complexity: "complexe",
    estimatedDuration: "2-4 mois",
    deliverables: ["Auto-evaluation SAQ", "Segmentation reseau paiement", "Rapport de conformite PCI"],
    source: "nouveau",
  },
];

// ── Helper functions ──

/**
 * Retourne les playbooks pour une sous-section specifique d'un departement
 */
export function getPlaybooksForSection(botCode: string, sectionId: string): BlueprintPlaybook[] {
  return BLUEPRINT_PLAYBOOKS.filter(
    (p) => p.botCode === botCode && p.blueprintSection === sectionId
  );
}

/**
 * Retourne tous les playbooks d'un departement
 */
export function getPlaybooksForBot(botCode: string): BlueprintPlaybook[] {
  return BLUEPRINT_PLAYBOOKS.filter((p) => p.botCode === botCode);
}

/**
 * Retourne les playbooks applicables a une phase de maturite donnee
 */
export function getPlaybooksForPhase(phase: string): BlueprintPlaybook[] {
  return BLUEPRINT_PLAYBOOKS.filter(
    (p) => p.phases.indexOf(phase as "startup" | "scaleup" | "exitup") !== -1
  );
}

/**
 * Retourne les playbooks applicables a un tier de taille donne
 * (tier >= minTier && tier <= maxTier)
 */
export function getPlaybooksForTier(tier: number): BlueprintPlaybook[] {
  return BLUEPRINT_PLAYBOOKS.filter((p) => tier >= p.minTier && tier <= p.maxTier);
}
